# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run Build
          command: go run main.go
      - run:
          name: List
          command: cd result && ls -al
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/*
            - result/*
            - simHash/*
            - spider/*
            - utils/*
            - .gitignore
            - go.mod
            - go.sum
            - main.go
            - readme.md
          

  deploy:
    # refs: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
    docker:
      - image: node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "auto@git.com"
            git config user.name "auto"
      - add_ssh_keys:
          fingerprints:
            - "9b:1d:d5:eb:5d:fb:e4:53:5b:d3:14:49:23:ac:53:ed"
      - run:
          name: List
          command: ls -al
      - run:
          name: Deploy
          command: gh-pages --dist . --dotfiles --message "[skip ci] Auto Updates" --branch main

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main