# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run Build
          command: go run main.go
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/*
            - result/*
            - simHash/*
            - spider/*
            - .gitignore
            - go.mod
            - go.sum
            - main.go
            - readme.md
          

  deploy:
    # refs: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
    docker:
      - image: node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "82163514@qq.com"
            git config user.name "echosoar"
      - add_ssh_keys:
          fingerprints:
            - "38:5f:b9:68:2c:e6:ad:a4:32:49:6b:bd:31:e7:f8:ce"
      - run:
          name: Deploy
          command: gh-pages --dist result readme.md --dotfiles --message "[skip ci] Auto Updates" 

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main